global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "gateway:8222" ]

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "auth-service:8081" ]

  - job_name: "booking-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "booking-service:8084" ]

  - job_name: "accommodation-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "accommodation-service:8082" ]

  - job_name: "address-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "address-service:8083" ]

  - job_name: "payment-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "payment-service:8085" ]

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "notification-service:8086" ]

