[versions]
mapstruct = "1.5.5.Final"
lombok = "1.18.32"
postgres = "42.7.3"
springcloud = "2024.0.0"

[libraries]
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstructProcessor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }

springcloudBom = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springcloud" }
